<<<<<<< HEAD
2023-03-20 17:50:40,859 Inciando Proceso
2023-03-20 17:50:40,887 Inciando Proceso
2023-03-20 17:50:40,887 Inciando Proceso
2023-03-20 17:50:40,887 Inciando Proceso
2023-03-20 17:50:40,899 Inciando Proceso
2023-03-20 17:50:40,918 Bad Request: /
2023-03-20 17:50:40,998 Invalid HTTP_HOST header: '181.49.241.226:4084'. You may need to add '181.49.241.226' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/var/www/appsdjango/venvinterface/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/var/www/appsdjango/venvinterface/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/var/www/appsdjango/venvinterface/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/var/www/appsdjango/venvinterface/lib/python3.10/site-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '181.49.241.226:4084'. You may need to add '181.49.241.226' to ALLOWED_HOSTS.
2023-03-20 17:50:41,023 Bad Request: /favicon.ico
=======
2023-03-20 09:14:11,390 Inciando Proceso
2023-03-20 09:14:12,760 Inciando Proceso
2023-03-20 09:14:12,760 Inciando Proceso
2023-03-20 09:14:12,760 Inciando Proceso
2023-03-20 09:14:12,860 Inciando Proceso
>>>>>>> e25c8e459e5cf05ffaf5f8a69b25336ad569aafd
